package commonInfrastructures;

/**
 * Message Types
 */
public enum MessageType {
    INFORM_PLANE_READY_FOR_BOARDING,
    WAIT_FOR_ALL_IN_BOARD,
    FLY_TO_DESTINATION_POINT,
    ANNOUNCE_ARRIVAL,
    FLY_TO_DEPARTURE_POINT,
    PARK_AT_TRANSFER_GATE,
    PREPARE_FOR_PASS_BOARDING,
    INFORM_PLANE_READY_TO_TAKEOFF,
    CHECK_DOCUMENTS,
    WAIT_FOR_NEXT_PASSENGER,
    WAIT_FOR_NEXT_FLIGHT,
    TRAVEL_TO_AIRPORT,
    WAIT_IN_QUEUE,
    SHOW_DOCUMENTS,
    BOARD_THE_PLANE,
    WAIT_FOR_END_OF_FLIGHT,
    LEAVE_THE_PLANE,
    SUM_UP,
    REPORT_INITIAL_STATUS,
    REPORT_STATUS,
    SET_PILOT_STATE,
    SET_HOSTTES_STATE,
    SET_PASSENGER_STATE,
    IS_INFORM_PLANE,
    STOP
}
